name: Build and Push React App to AWS ECR

on:
  push:
    branches: [ main ]
  workflow_dispatch:

env:
  AWS_REGION: us-east-1
  ECR_REPOSITORY: customer-crud-app

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      # Checkout Source Code
      - name: Check out repository
        uses: actions/checkout@v4

      # Configure AWS Credentials
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ env.AWS_REGION }}

      # Login to Amazon ECR
      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v2

      # Build Docker Image
      - name: Build Docker image
        run: |
          docker build -t $ECR_REPOSITORY:latest .

      # Tag Docker Image
      - name: Tag image
        run: |
          docker tag $ECR_REPOSITORY:latest ${{ steps.login-ecr.outputs.registry }}/${{ env.ECR_REPOSITORY }}:latest

      # Push Docker Image
      - name: Push to ECR
        run: |
          docker push ${{ steps.login-ecr.outputs.registry }}/${{ env.ECR_REPOSITORY }}:latest

      # Print success message
      - name: Done
        run: echo "ðŸŽ‰ Docker image successfully pushed to ECR!"
