name: Build and Push React App to AWS ECR

on:
  push:
    branches: [ main ]
  workflow_dispatch:

env:  
  ECR_REPOSITORY: customer-crud-app

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      # Checkout Source Code
      - name: Check out repository
        uses: actions/checkout@v4

      # Configure AWS Credentials
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: ${{ secrets.AWS_ROLE_ARN }}
          aws-region: ${{ secrets.AWS_REGION }}

      # Login to Amazon ECR
      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v2

      # Build Docker Image
      - name: Build Docker image
        run: |
          docker build -t $ECR_REPOSITORY:latest .

      # Tag Docker Image
      - name: Tag image
        run: |
          docker tag $ECR_REPOSITORY:latest ${{ steps.login-ecr.outputs.registry }}/${{ env.ECR_REPOSITORY }}:latest

      # Push Docker Image
      - name: Push to ECR
        run: |
          docker push ${{ steps.login-ecr.outputs.registry }}/${{ env.ECR_REPOSITORY }}:latest

      # Print success message
      - name: Done
        run: echo "ðŸŽ‰ Docker image successfully pushed to ECR!"
